"""autogenerating add phonenumber

Revision ID: 3cd44d1a879c
Revises: 1a5ee703ba7c
Create Date: 2022-03-02 00:48:50.921594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd44d1a879c'
down_revision = '1a5ee703ba7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
